### ISSUE TITLE
Failing to open the projects

### ISSUE THREAD

**Issue by Pacha1** [csprousers/examples#4]
Hello i have cspro 7.5 installed and i am failing to open the example projects. I have noticed that @Oryxamus updated the version number  to 7.6 . I have tried looking for this version but i cant find any link for it. How can i find it or open the example files.

**Comment by jhandley** [comment]
Use the examples that come with CSPro. This repository is for the developers of CSPro to make changes to the examples. You can find the examples directory from the Help menu in CSPro. If you have further questions email cspro@lists.census.gov with questions. This is not the place to get CSPro help.

**Comment by Pacha1** [comment]
Thank you. this is well noted
